import type { ThemeSettings, ThemeColors } from "@/types";

// ===== DEFAULT COLORS — matches globals.css exactly =====
export const DEFAULT_LIGHT_COLORS: ThemeColors = {
  primary: "#1a5c38",
  primaryLight: "#2d8a52",
  primaryDark: "#0f3d24",
  secondary: "#c8860a",
  accent: "#e8f5ee",
  text: "#1a1a1a",
  textMuted: "#6b7280",
  bg: "#ffffff",
  bgAlt: "#f8faf9",
  border: "#e5e7eb",
};

export const DEFAULT_DARK_COLORS: ThemeColors = {
  primary: "#2d8a52",
  primaryLight: "#3da564",
  primaryDark: "#1a5c38",
  secondary: "#d4a037",
  accent: "#1a2e22",
  text: "#f1f5f9",
  textMuted: "#94a3b8",
  bg: "#0f172a",
  bgAlt: "#1e293b",
  border: "#334155",
};

export const DEFAULT_THEME: ThemeSettings = {
  light: DEFAULT_LIGHT_COLORS,
  dark: DEFAULT_DARK_COLORS,
  typography: {
    fontPrimary: "Nunito",
    fontHeading: "Merriweather",
  },
  layout: {
    borderRadius: 12,
  },
};

// ===== CSS VARIABLE MAPPING =====
export const COLOR_TO_CSS_VAR: Record<keyof ThemeColors, string> = {
  primary: "--color-primary",
  primaryLight: "--color-primary-light",
  primaryDark: "--color-primary-dark",
  secondary: "--color-secondary",
  accent: "--color-accent",
  text: "--color-text",
  textMuted: "--color-text-muted",
  bg: "--color-bg",
  bgAlt: "--color-bg-alt",
  border: "--color-border",
};

// ===== COLOR LABELS (Turkish) =====
export const COLOR_LABELS: Record<keyof ThemeColors, { label: string; description: string }> = {
  primary: { label: "Ana Renk", description: "Butonlar, linkler ve vurgular" },
  primaryLight: { label: "Ana Renk (Açık)", description: "Hover ve açık tonlar" },
  primaryDark: { label: "Ana Renk (Koyu)", description: "Hover koyu ve başlıklar" },
  secondary: { label: "İkincil Renk", description: "Altın/turuncu vurgular" },
  accent: { label: "Aksan Renk", description: "Açık arka plan vurguları" },
  text: { label: "Ana Metin", description: "Başlıklar ve ana metin rengi" },
  textMuted: { label: "Soluk Metin", description: "Alt yazılar ve açıklamalar" },
  bg: { label: "Arka Plan", description: "Ana sayfa arka planı" },
  bgAlt: { label: "Alternatif Arka Plan", description: "Bölüm ayırıcı arka plan" },
  border: { label: "Kenarlık", description: "Kartlar ve çizgiler" },
};

// ===== PRESET THEMES =====
export const PRESET_THEMES: Record<string, { label: string; description: string; category?: string; light: ThemeColors; dark: ThemeColors }> = {
  // ——— Genel ———
  "yesil-doga": {
    label: "Yeşil Doğa",
    description: "Varsayılan doğa teması",
    category: "Genel",
    light: { ...DEFAULT_LIGHT_COLORS },
    dark: { ...DEFAULT_DARK_COLORS },
  },
  "mavi-okyanus": {
    label: "Mavi Okyanus",
    description: "Profesyonel mavi tema",
    category: "Genel",
    light: {
      primary: "#1e40af",
      primaryLight: "#3b82f6",
      primaryDark: "#1e3a8a",
      secondary: "#f59e0b",
      accent: "#eff6ff",
      text: "#1e293b",
      textMuted: "#64748b",
      bg: "#ffffff",
      bgAlt: "#f8fafc",
      border: "#e2e8f0",
    },
    dark: {
      primary: "#3b82f6",
      primaryLight: "#60a5fa",
      primaryDark: "#1e40af",
      secondary: "#fbbf24",
      accent: "#1e293b",
      text: "#f1f5f9",
      textMuted: "#94a3b8",
      bg: "#0f172a",
      bgAlt: "#1e293b",
      border: "#334155",
    },
  },
  "kirmizi-ates": {
    label: "Kırmızı Ateş",
    description: "Enerjik kırmızı tema",
    category: "Genel",
    light: {
      primary: "#dc2626",
      primaryLight: "#ef4444",
      primaryDark: "#991b1b",
      secondary: "#ea580c",
      accent: "#fef2f2",
      text: "#1c1917",
      textMuted: "#78716c",
      bg: "#ffffff",
      bgAlt: "#fafaf9",
      border: "#e7e5e4",
    },
    dark: {
      primary: "#ef4444",
      primaryLight: "#f87171",
      primaryDark: "#dc2626",
      secondary: "#f97316",
      accent: "#292524",
      text: "#fafaf9",
      textMuted: "#a8a29e",
      bg: "#1c1917",
      bgAlt: "#292524",
      border: "#44403c",
    },
  },
  "mor-gece": {
    label: "Mor Gece",
    description: "Şık mor tema",
    category: "Genel",
    light: {
      primary: "#7c3aed",
      primaryLight: "#a78bfa",
      primaryDark: "#5b21b6",
      secondary: "#06b6d4",
      accent: "#f5f3ff",
      text: "#1e1b4b",
      textMuted: "#6b7280",
      bg: "#ffffff",
      bgAlt: "#faf5ff",
      border: "#e9d5ff",
    },
    dark: {
      primary: "#a78bfa",
      primaryLight: "#c4b5fd",
      primaryDark: "#7c3aed",
      secondary: "#22d3ee",
      accent: "#1e1b4b",
      text: "#f5f3ff",
      textMuted: "#a5b4fc",
      bg: "#0f0a1e",
      bgAlt: "#1e1b4b",
      border: "#3730a3",
    },
  },
  "turuncu-gunes": {
    label: "Turuncu Güneş",
    description: "Sıcak turuncu tema",
    category: "Genel",
    light: {
      primary: "#ea580c",
      primaryLight: "#f97316",
      primaryDark: "#c2410c",
      secondary: "#0891b2",
      accent: "#fff7ed",
      text: "#1c1917",
      textMuted: "#78716c",
      bg: "#ffffff",
      bgAlt: "#fffbeb",
      border: "#fed7aa",
    },
    dark: {
      primary: "#f97316",
      primaryLight: "#fb923c",
      primaryDark: "#ea580c",
      secondary: "#22d3ee",
      accent: "#431407",
      text: "#fef3c7",
      textMuted: "#a8a29e",
      bg: "#1c1917",
      bgAlt: "#292524",
      border: "#44403c",
    },
  },

  // ——— Devlet ———
  "cumhurbaskanligi": {
    label: "Cumhurbaşkanlığı",
    description: "Bayrak kırmızısı ve altın tema",
    category: "Devlet",
    light: {
      primary: "#E30A17",
      primaryLight: "#F44336",
      primaryDark: "#B71C1C",
      secondary: "#C8A951",
      accent: "#FFF8E1",
      text: "#212121",
      textMuted: "#616161",
      bg: "#FFFFFF",
      bgAlt: "#F5F5F5",
      border: "#E0E0E0",
    },
    dark: {
      primary: "#F44336",
      primaryLight: "#EF5350",
      primaryDark: "#E30A17",
      secondary: "#D4B96A",
      accent: "#2A1015",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "e-devlet": {
    label: "e-Devlet",
    description: "Resmi koyu mavi tema",
    category: "Devlet",
    light: {
      primary: "#1A3C6E",
      primaryLight: "#2B5EA7",
      primaryDark: "#0F2A50",
      secondary: "#E30A17",
      accent: "#EEF2F7",
      text: "#1A2332",
      textMuted: "#5A6B7E",
      bg: "#FFFFFF",
      bgAlt: "#EEF2F7",
      border: "#C5D0DC",
    },
    dark: {
      primary: "#2B5EA7",
      primaryLight: "#4A7CC7",
      primaryDark: "#1A3C6E",
      secondary: "#F44336",
      accent: "#0F1A2E",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "milli-egitim": {
    label: "Milli Eğitim",
    description: "Eğitim mavisi tema",
    category: "Devlet",
    light: {
      primary: "#1565C0",
      primaryLight: "#42A5F5",
      primaryDark: "#0D47A1",
      secondary: "#FF8F00",
      accent: "#E3F2FD",
      text: "#0D2137",
      textMuted: "#546E7A",
      bg: "#FFFFFF",
      bgAlt: "#E3F2FD",
      border: "#B0BEC5",
    },
    dark: {
      primary: "#42A5F5",
      primaryLight: "#64B5F6",
      primaryDark: "#1565C0",
      secondary: "#FFB300",
      accent: "#0D1B2A",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "saglik": {
    label: "Sağlık Bakanlığı",
    description: "Sağlık mavisi ve turkuaz",
    category: "Devlet",
    light: {
      primary: "#0277BD",
      primaryLight: "#00ACC1",
      primaryDark: "#01579B",
      secondary: "#2E7D32",
      accent: "#E0F7FA",
      text: "#0A1929",
      textMuted: "#607D8B",
      bg: "#FFFFFF",
      bgAlt: "#E0F7FA",
      border: "#B2EBF2",
    },
    dark: {
      primary: "#00ACC1",
      primaryLight: "#26C6DA",
      primaryDark: "#0277BD",
      secondary: "#43A047",
      accent: "#0A1929",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Güvenlik ———
  "emniyet": {
    label: "Emniyet",
    description: "Polis laciverti ve altın",
    category: "Güvenlik",
    light: {
      primary: "#1A237E",
      primaryLight: "#283593",
      primaryDark: "#0D1042",
      secondary: "#FFD600",
      accent: "#E8EAF6",
      text: "#0D1042",
      textMuted: "#5C6BC0",
      bg: "#FFFFFF",
      bgAlt: "#E8EAF6",
      border: "#C5CAE9",
    },
    dark: {
      primary: "#283593",
      primaryLight: "#3F51B5",
      primaryDark: "#1A237E",
      secondary: "#FFEA00",
      accent: "#0D1042",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "jandarma": {
    label: "Jandarma",
    description: "Askeri yeşil tema",
    category: "Güvenlik",
    light: {
      primary: "#2E5730",
      primaryLight: "#4E7A51",
      primaryDark: "#1B4332",
      secondary: "#8B1A1A",
      accent: "#E8F5E9",
      text: "#0A1F0B",
      textMuted: "#4E7A51",
      bg: "#FFFFFF",
      bgAlt: "#E8F5E9",
      border: "#C8E6C9",
    },
    dark: {
      primary: "#4E7A51",
      primaryLight: "#6DA670",
      primaryDark: "#2E5730",
      secondary: "#C62828",
      accent: "#0A1F0B",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Belediye ———
  "belediye-kirmizi": {
    label: "Belediye Klasik",
    description: "Klasik kırmızı belediye teması",
    category: "Belediye",
    light: {
      primary: "#C62828",
      primaryLight: "#E53935",
      primaryDark: "#B71C1C",
      secondary: "#1A237E",
      accent: "#FFEBEE",
      text: "#1A1A1A",
      textMuted: "#616161",
      bg: "#FFFFFF",
      bgAlt: "#F5F5F5",
      border: "#BDBDBD",
    },
    dark: {
      primary: "#E53935",
      primaryLight: "#EF5350",
      primaryDark: "#C62828",
      secondary: "#3949AB",
      accent: "#2A1015",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "belediye-mavi": {
    label: "Belediye Modern",
    description: "Modern mavi belediye teması",
    category: "Belediye",
    light: {
      primary: "#1565C0",
      primaryLight: "#1E88E5",
      primaryDark: "#0D47A1",
      secondary: "#FF8F00",
      accent: "#E3F2FD",
      text: "#0D2137",
      textMuted: "#546E7A",
      bg: "#FFFFFF",
      bgAlt: "#E3F2FD",
      border: "#90CAF9",
    },
    dark: {
      primary: "#1E88E5",
      primaryLight: "#42A5F5",
      primaryDark: "#1565C0",
      secondary: "#FFB300",
      accent: "#0D1B2A",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "belediye-turkuaz": {
    label: "Belediye Turkuaz",
    description: "Turkuaz belediye teması",
    category: "Belediye",
    light: {
      primary: "#00838F",
      primaryLight: "#00ACC1",
      primaryDark: "#006064",
      secondary: "#EF6C00",
      accent: "#E0F7FA",
      text: "#004D40",
      textMuted: "#607D8B",
      bg: "#FFFFFF",
      bgAlt: "#E0F7FA",
      border: "#80DEEA",
    },
    dark: {
      primary: "#00ACC1",
      primaryLight: "#26C6DA",
      primaryDark: "#00838F",
      secondary: "#FB8C00",
      accent: "#0A2029",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Dernek / STK ———
  "dernek-mavi": {
    label: "Dernek Klasik Mavi",
    description: "Güvenilir kurumsal mavi",
    category: "Dernek / STK",
    light: {
      primary: "#1565C0",
      primaryLight: "#42A5F5",
      primaryDark: "#0D47A1",
      secondary: "#4CAF50",
      accent: "#E8F0FE",
      text: "#1A2B4A",
      textMuted: "#5F6B7A",
      bg: "#FFFFFF",
      bgAlt: "#E8F0FE",
      border: "#B8C9E0",
    },
    dark: {
      primary: "#42A5F5",
      primaryLight: "#64B5F6",
      primaryDark: "#1565C0",
      secondary: "#66BB6A",
      accent: "#0D1B2A",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "hayir-dernegi": {
    label: "Hayır Derneği",
    description: "Zümrüt yeşili yardımlaşma",
    category: "Dernek / STK",
    light: {
      primary: "#00897B",
      primaryLight: "#26A69A",
      primaryDark: "#00695C",
      secondary: "#FF8F00",
      accent: "#E0F2F1",
      text: "#0A2E29",
      textMuted: "#4D8077",
      bg: "#FFFFFF",
      bgAlt: "#E0F2F1",
      border: "#B2DFDB",
    },
    dark: {
      primary: "#26A69A",
      primaryLight: "#4DB6AC",
      primaryDark: "#00897B",
      secondary: "#FFB300",
      accent: "#0A2E29",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "egitim-vakfi": {
    label: "Eğitim Vakfı",
    description: "Akademik mor tema",
    category: "Dernek / STK",
    light: {
      primary: "#5E35B1",
      primaryLight: "#7E57C2",
      primaryDark: "#4527A0",
      secondary: "#FFB300",
      accent: "#EDE7F6",
      text: "#1A0A3E",
      textMuted: "#7E6B9B",
      bg: "#FFFFFF",
      bgAlt: "#EDE7F6",
      border: "#D1C4E9",
    },
    dark: {
      primary: "#7E57C2",
      primaryLight: "#9575CD",
      primaryDark: "#5E35B1",
      secondary: "#FFC107",
      accent: "#1A0A3E",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "insani-yardim": {
    label: "İnsani Yardım",
    description: "Kızılay tarzı kırmızı",
    category: "Dernek / STK",
    light: {
      primary: "#D32F2F",
      primaryLight: "#E53935",
      primaryDark: "#B71C1C",
      secondary: "#FFFFFF",
      accent: "#FFEBEE",
      text: "#1A1A1A",
      textMuted: "#616161",
      bg: "#FFFFFF",
      bgAlt: "#FFEBEE",
      border: "#FFCDD2",
    },
    dark: {
      primary: "#E53935",
      primaryLight: "#EF5350",
      primaryDark: "#D32F2F",
      secondary: "#E0E0E0",
      accent: "#2A1015",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "cevre-dernegi": {
    label: "Çevre Derneği",
    description: "Yaprak yeşili doğa teması",
    category: "Dernek / STK",
    light: {
      primary: "#388E3C",
      primaryLight: "#66BB6A",
      primaryDark: "#2E7D32",
      secondary: "#795548",
      accent: "#F1F8E9",
      text: "#1B3A1C",
      textMuted: "#6D5B4E",
      bg: "#FFFFFF",
      bgAlt: "#F1F8E9",
      border: "#C5E1A5",
    },
    dark: {
      primary: "#66BB6A",
      primaryLight: "#81C784",
      primaryDark: "#388E3C",
      secondary: "#8D6E63",
      accent: "#1B3A1C",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "spor-kulubu": {
    label: "Spor Kulübü",
    description: "Enerji mavisi spor teması",
    category: "Dernek / STK",
    light: {
      primary: "#0277BD",
      primaryLight: "#039BE5",
      primaryDark: "#01579B",
      secondary: "#FF6D00",
      accent: "#E1F5FE",
      text: "#002F6C",
      textMuted: "#546E7A",
      bg: "#FFFFFF",
      bgAlt: "#E1F5FE",
      border: "#B3E5FC",
    },
    dark: {
      primary: "#039BE5",
      primaryLight: "#29B6F6",
      primaryDark: "#0277BD",
      secondary: "#FF9100",
      accent: "#002F6C",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "kultur-sanat": {
    label: "Kültür / Sanat",
    description: "Bordo kültür teması",
    category: "Dernek / STK",
    light: {
      primary: "#880E4F",
      primaryLight: "#AD1457",
      primaryDark: "#6A1B4D",
      secondary: "#FFB300",
      accent: "#FCE4EC",
      text: "#2C0519",
      textMuted: "#757575",
      bg: "#FFFFFF",
      bgAlt: "#FCE4EC",
      border: "#F8BBD0",
    },
    dark: {
      primary: "#AD1457",
      primaryLight: "#D81B60",
      primaryDark: "#880E4F",
      secondary: "#FFC107",
      accent: "#2C0519",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Sağlık ———
  "hastane": {
    label: "Hastane",
    description: "Sağlık merkezi mavi teması",
    category: "Sağlık",
    light: {
      primary: "#0288D1",
      primaryLight: "#4FC3F7",
      primaryDark: "#01579B",
      secondary: "#E53935",
      accent: "#E1F5FE",
      text: "#0A2540",
      textMuted: "#546E7A",
      bg: "#FFFFFF",
      bgAlt: "#E1F5FE",
      border: "#B3E5FC",
    },
    dark: {
      primary: "#4FC3F7",
      primaryLight: "#81D4FA",
      primaryDark: "#0288D1",
      secondary: "#EF5350",
      accent: "#0A2540",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Eğitim ———
  "universite": {
    label: "Üniversite",
    description: "Akademik lacivert tema",
    category: "Eğitim",
    light: {
      primary: "#1A237E",
      primaryLight: "#3949AB",
      primaryDark: "#0D1042",
      secondary: "#FFD54F",
      accent: "#E8EAF6",
      text: "#0D1042",
      textMuted: "#5C6BC0",
      bg: "#FFFFFF",
      bgAlt: "#E8EAF6",
      border: "#C5CAE9",
    },
    dark: {
      primary: "#3949AB",
      primaryLight: "#5C6BC0",
      primaryDark: "#1A237E",
      secondary: "#FFE082",
      accent: "#0D1042",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },

  // ——— Dini Kurum ———
  "diyanet": {
    label: "Diyanet / Cami",
    description: "İslam yeşili tema",
    category: "Dini Kurum",
    light: {
      primary: "#1B5E20",
      primaryLight: "#2E7D32",
      primaryDark: "#0D3B11",
      secondary: "#D4A843",
      accent: "#E8F5E9",
      text: "#0A1F0B",
      textMuted: "#4E7A51",
      bg: "#FFFFFF",
      bgAlt: "#E8F5E9",
      border: "#C8E6C9",
    },
    dark: {
      primary: "#2E7D32",
      primaryLight: "#43A047",
      primaryDark: "#1B5E20",
      secondary: "#E0BE6A",
      accent: "#0A1F0B",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
  "kuran-kursu": {
    label: "Kuran Kursu",
    description: "Zümrüt yeşili dini tema",
    category: "Dini Kurum",
    light: {
      primary: "#00695C",
      primaryLight: "#00897B",
      primaryDark: "#004D40",
      secondary: "#C8A415",
      accent: "#E0F2F1",
      text: "#003D33",
      textMuted: "#4D8077",
      bg: "#FFFDE7",
      bgAlt: "#E0F2F1",
      border: "#B2DFDB",
    },
    dark: {
      primary: "#00897B",
      primaryLight: "#26A69A",
      primaryDark: "#00695C",
      secondary: "#D4B82F",
      accent: "#003D33",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      bg: "#0F172A",
      bgAlt: "#1E293B",
      border: "#334155",
    },
  },
};

// ===== AVAILABLE FONTS =====
export const AVAILABLE_FONTS = {
  body: [
    { value: "Nunito", label: "Nunito" },
    { value: "Inter", label: "Inter" },
    { value: "Poppins", label: "Poppins" },
    { value: "Open Sans", label: "Open Sans" },
    { value: "Roboto", label: "Roboto" },
    { value: "Lato", label: "Lato" },
    { value: "Source Sans 3", label: "Source Sans 3" },
    { value: "Montserrat", label: "Montserrat" },
  ],
  heading: [
    { value: "Merriweather", label: "Merriweather" },
    { value: "Playfair Display", label: "Playfair Display" },
    { value: "Lora", label: "Lora" },
    { value: "Poppins", label: "Poppins" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Raleway", label: "Raleway" },
    { value: "Oswald", label: "Oswald" },
    { value: "Nunito", label: "Nunito" },
  ],
};
